workspace:
  base: /code

pipeline:
  unit-tests:
    image: node:latest
    commands:
      - yarn install
      - yarn test
    when:
      event: [push, tag]

  build-assets:
    image: node:latest
    environment:
      - NODE_ENV=production
      - API_URL=https://api.staging.bonde.org
      - GRAPHQL_URL=https://data.staging.bonde.org
      - APP_DOMAIN=staging.bonde.org
      - PAGARME_KEY=${STAG_PAGARME_KEY}
      - AWS_BUCKET=${STAG_AWS_BUCKET}
      - SENTRY_DSN_PUBLIC=${STAG_SENTRY_DSN_PUBLIC}
      - GOOGLE_FONTS_API_KEY=${STAG_GOOGLE_FONTS_API_KEY}
    commands:
      - mkdir build
      - yarn run build:client
      - yarn run build:server
    when:
      status: success
      branch: [hotfix-*, release-*, feature-*, develop]

  publish-docker-staging:
    image: plugins/docker
    group: publish
    repo: nossas/bonde-client
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_BRANCH}
    when:
      status: success
      branch: [hotfix-*, release-*, feature-*, develop]

  publish-s3-staging:
    image: plugins/s3-sync:1
    group: publish
    bucket: bonde-assets-staging
    region: sa-east-1
    source: public
    target: /
    delete: true
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    acl:
      "*": public-read
    content_type:
      ".ttf": application/x-font-ttf
      ".eot": application/vnd.ms-fontobject
      ".png": image/png
      ".otf": application/x-font-opentype
      ".woff": application/font-woff
      ".woff2": application/font-woff2
      ".svg": image/svg+xml
    content_encoding:
      ".js": gzip
      ".css": gzip
      ".svg": gzip
    cache_control: "public, max-age: 31536000"
    when:
      status: success
      branch: [hotfix-*, release-*, feature-*, develop]

  publish-rancher-staging:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: staging/client
    docker_image: nossas/bonde-client:${DRONE_BRANCH}
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      branch: [hotfix-*, release-*, feature-*, develop]

  build-docker-production:
    image: plugins/docker
    repo: nossas/bonde-client
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_TAG##v}
    build_args:
      - NODE_ENV=production
      - APP_DOMAIN=bonde.org
      - API_URL=https://api.bonde.org
      - AWS_BUCKET=bonde-assets
      - GRAPHQL_URL=https://data.bonde.org/graphql
    when:
      status: success
      event: tag

  publish-dokku-production:
    image: appleboy/drone-ssh
    host: ssh.bonde.org
    username: ubuntu
    command_timeout: 360
    port: 22
    secrets: [ ssh_key ]
    script:
      - sudo docker pull nossas/bonde-client:${DRONE_TAG##v}
      - sudo docker tag nossas/bonde-client:${DRONE_TAG##v} dokku/0-client:latest
      - sudo docker tag nossas/bonde-client:${DRONE_TAG##v} dokku/app-client:latest
      - dokku tags:deploy 0-client latest
      - dokku tags:deploy app-client latest
      - dokku --rm run app-client yarn run build:client
      - dokku --rm run app-client yarn run build:server
      - dokku ps:restart 0-client
      - dokku ps:restart app-client
    when:
      status: success
      event: tag

  notify:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: n_tech
    username: CI - ${DRONE_REPO_NAME}
    when:
      event: [ push, tag, build, publish, deployment, pull_request ]
      status: [ success, failure ]
