pipeline:
  build:
    image: node:latest
    commands:
      - yarn install
      - yarn test
    when:
      event: [push, tag]

  publish-staging:
    image: plugins/docker
    repo: nossas/bonde-client
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_BRANCH}
    when:
      status: success
      branch: [hotfix-*, release-*, feature-*, develop]

  deploy-staging:
    image: appleboy/drone-ssh
    host: staging.bonde.org
    username: ubuntu
    command_timeout: 360
    port: 22
    secrets: [ ssh_key ]
    script:
      - sudo docker pull nossas/bonde-client:${DRONE_BRANCH}
      - sudo docker tag nossas/bonde-client:${DRONE_BRANCH} dokku/0-client:latest
      - sudo docker tag nossas/bonde-client:${DRONE_BRANCH} dokku/app-client:latest
      - dokku tags:deploy 0-client latest
      - dokku tags:deploy app-client latest
      - dokku run 0-client yarn build:client && yarn build:server
    when:
      status: success
      branch: [hotfix-*, release-*, feature-*, develop]

  publish-production:
    image: plugins/docker
    repo: nossas/bonde-client
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_TAG##v}
    build_args:
      - NODE_ENV=production
      - APP_DOMAIN=bonde.org
      - API_URL=https://api.bonde.org
      - AWS_BUCKET=bonde-assets
      - GRAPHQL_URL=https://data.bonde.org/graphql
    when:
      status: success
      event: tag

  deploy-production:
    image: appleboy/drone-ssh
    host: ssh.bonde.org
    username: ubuntu
    command_timeout: 360
    port: 22
    secrets: [ ssh_key ]
    script:
      - sudo docker pull nossas/bonde-client:${DRONE_TAG##v}
      - sudo docker tag nossas/bonde-client:${DRONE_TAG##v} dokku/0-client:latest
      - sudo docker tag nossas/bonde-client:${DRONE_TAG##v} dokku/app-client:latest
      - dokku tags:deploy 0-client latest
      - dokku tags:deploy app-client latest
      - dokku run 0-client yarn build:client
      - dokku run 0-client yarn build:server
    when:
      status: success
      event: tag

  notify:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: n_tech
    username: CI - ${DRONE_REPO_NAME}
    when:
      event: [ push, tag, build, publish, deployment, pull_request ]
      status: [ success, failure ]
